export default function PrivacyPolicy() {
  return (
    <main style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px 80px" }}>
      <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
      <p style={{ color: "#888", marginBottom: 40, fontSize: 14 }}>
        PingWatch &mdash; Effective May 23, 2026
      </p>

      <Section title="1. Who We Are">
        PingWatch is operated by Vitalis &amp; Co Ltd (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;). You can reach
        us at{" "}
        <a href="mailto:hersh2025@vitalisnet.com" style={{ color: "#60a5fa" }}>
          hersh2025@vitalisnet.com
        </a>
        .
      </Section>

      <Section title="2. What We Collect">
        <p style={{ marginBottom: 12 }}>We collect only what is necessary to provide the service:</p>
        <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
          <li>
            <strong>Account data</strong> — your email address and hashed password when you register.
          </li>
          <li>
            <strong>Monitor data</strong> — the URLs and names you add to monitor, along with check
            results (status, response time, uptime percentage).
          </li>
          <li>
            <strong>Push notification token</strong> — a device token generated by Expo&rsquo;s push
            service, used only to deliver uptime alerts to your device.
          </li>
          <li>
            <strong>Pro purchase status</strong> — a flag stored locally on your device indicating
            whether you have an active Lifetime Pro plan.
          </li>
          <li>
            <strong>Payment data</strong> — processed entirely by Lemon Squeezy. We never see or store
            your card number, PayPal credentials, or billing address.
          </li>
        </ul>
      </Section>

      <Section title="3. What We Do Not Collect">
        <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
          <li>We do not collect your location.</li>
          <li>We do not access your contacts, camera, microphone, or files.</li>
          <li>We do not run third-party analytics or advertising SDKs.</li>
          <li>We do not sell, rent, or trade your data.</li>
        </ul>
      </Section>

      <Section title="4. How We Use Your Data">
        <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
          <li>Authenticate your account and keep your session secure.</li>
          <li>Run uptime checks on the URLs you configure.</li>
          <li>Send push notifications when a monitor changes state (DOWN or recovered).</li>
          <li>Verify your Lifetime Pro status when you sign in on a new device.</li>
          <li>Respond to support requests you send us.</li>
        </ul>
      </Section>

      <Section title="5. Third-Party Services">
        <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
          <li>
            <strong>Expo Push Service</strong> — delivers push notifications to Android and iOS
            devices. Subject to Expo&rsquo;s privacy policy.
          </li>
          <li>
            <strong>Lemon Squeezy</strong> — processes one-time payments for Lifetime Pro. Subject to
            Lemon Squeezy&rsquo;s privacy policy.
          </li>
        </ul>
        <p style={{ marginTop: 12 }}>
          We do not share your data with any other third parties.
        </p>
      </Section>

      <Section title="6. Data Retention">
        <p>
          Your account data and monitor history are retained for as long as your account is active. If
          you delete your account, all associated data is permanently removed within 30 days. Push
          notification tokens are invalidated immediately on sign-out.
        </p>
      </Section>

      <Section title="7. Security">
        <p>
          Passwords are hashed and never stored in plaintext. Auth tokens are stored in your
          device&rsquo;s encrypted secure storage (expo-secure-store). All communication between the
          app and our servers uses HTTPS.
        </p>
      </Section>

      <Section title="8. Your Rights">
        <p style={{ marginBottom: 12 }}>You have the right to:</p>
        <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
          <li>Access the personal data we hold about you.</li>
          <li>Correct inaccurate data.</li>
          <li>Request deletion of your account and all associated data.</li>
          <li>Withdraw consent at any time by deleting your account.</li>
        </ul>
        <p style={{ marginTop: 12 }}>
          To exercise any of these rights, email{" "}
          <a href="mailto:hersh2025@vitalisnet.com" style={{ color: "#60a5fa" }}>
            hersh2025@vitalisnet.com
          </a>
          .
        </p>
      </Section>

      <Section title="9. Children">
        <p>
          PingWatch is not directed at children under 13. We do not knowingly collect personal data
          from children. If you believe a child has provided us data, contact us and we will delete it
          promptly.
        </p>
      </Section>

      <Section title="10. Changes to This Policy">
        <p>
          If we make material changes to this policy, we will update the effective date above. Continued
          use of PingWatch after changes are posted constitutes acceptance of the updated policy.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions or requests?{" "}
          <a href="mailto:hersh2025@vitalisnet.com" style={{ color: "#60a5fa" }}>
            hersh2025@vitalisnet.com
          </a>
        </p>
      </Section>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 17, fontWeight: 600, marginBottom: 12, color: "#e2e8f0" }}>{title}</h2>
      <div style={{ color: "#b0b8c4", fontSize: 15, lineHeight: 1.8 }}>{children}</div>
    </section>
  );
}
